version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - data:/var/usr/src/data
    links:
      - rabbitmq
  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
    volumes:
      - data:/var/usr/src/data
    links:
      - rabbitmq
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
    links:
      - rabbitmq
  plot:
    build:
      context: ./plot
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
      - metric
    volumes:
      - data:/var/usr/src/data
volumes:
  data:
    name: data
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data"
